# AprilTag 3 code parameters
# Find descriptions in apriltag/include/apriltag.h:struct apriltag_detector
#                      apriltag/include/apriltag.h:struct apriltag_family
tag_family:        'tag16h5'  # options: tag36h11, tag25h9, tag16h5
tag_threads:       4          # default: 4
tag_border:        0.7518     # default: 1.0
tag_decimate:      1.0        # default: 1.0
tag_blur:          0.8        # default: 0.0
tag_refine_edges:  1          # default: 1
tag_debug:         0          # default: 0
tag_refine_decode: 0          # default: 0
tag_refine_pose:   0          # default: 0
# Other parameters
publish_tf:        true       # default: false
remove_duplicates: true       # default: true